frontend/models/Category.php
<?php

namespace frontend\models;

use Yii;
use yii\db\ActiveQuery;
use yii2tech\ar\softdelete\SoftDeleteBehavior;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property string $categoryName
 * @method softDelete
 */
class Category extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @return ActiveQuery
     */
    public static function findActive()
    {
        $query = self::find();
        return $query->andWhere(['is', 'deletedAt', null]);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['categoryName'], 'required'],
            [['categoryName'], 'string', 'max' => 200],
        ];
    }

    public function behaviors()
    {
        return [
            'softDeleteBehavior' => [
                'class' => SoftDeleteBehavior::class,
                'softDeleteAttributeValues' => [
                    'deletedAt' => function ($model) {
                        return date('Y-m-d');
                    }
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'categoryName' => 'Category Name',
        ];
    }

    public function getRestaurants(): ActiveQuery
    {
        return $this->hasMany(\frontend\models\Restaurants::className(), ['categoryId' => 'id']);
    }
}

frontend/controllers/RocketChatController.php
<?php

namespace frontend\controllers;

use frontend\rocketChat\filters\AuthToken;
use frontend\rocketChat\models\Request;
use TheIconic\Tracking\GoogleAnalytics\Analytics;
use yii\rest\Controller;

class RocketChatController extends Controller
{
    public function behaviors()
    {
        $behaviours = parent::behaviors();
        $behaviours['auth'] = [
            'class' => AuthToken::className(),
            'token' => \Yii::$app->params['rocketChatBotToken']
        ];
        return $behaviours;
    }

    /**
     * @return array|Request
     * @throws \yii\base\InvalidConfigException
     */
    public function actionIndex()
    {
        $request = \Yii::$app->request->getBodyParams();
        $message = Request::factoryFromArray($request);

        if (!$message->validate()) {
            return $message;
        }

        $command = \frontend\rocketChat\commands\ChainOfCommands::getCommandForInput($message->text);
        $body = $command->execute($message);

        //todo mmo - moze to tez zrobic na zdarzeniu? Albo na afterAction?
        /** @var Analytics $ga */
        $ga = \Yii::$container->get(\TheIconic\Tracking\GoogleAnalytics\Analytics::class);
        $ga->setEventCategory('Bot')
            ->setEventAction('call')
            ->setEventValue(get_class($command))
            ->sendEvent();

        return [
            'text' => $body
        ];
    }
}

frontend/views/rocket-chat/commands/help.php
Dostępne polecenia to:
* info - zwraca id użytkownika i informacje o powiązaniu (lub nie) konta z ssorder

* order - informacja o dzisiejszym zamówieniu lub braku

* last - informacja o ostatnim zrealizowanym zamówieniu (ale nie w dniu dzisiejszym)

* history - 'data od' [data do]
Gdzie obsługiwane formaty daty to:
YYYY-MM-DD
-5days (data sprzed 5dni)

Przykłady:
`history -5days` Wszystkie zamówienia sprzed 5 dni
`history -5days today` Wszystkie zamówienia od 5 dni wstecz do dnia dzisiejszego włącznie

* reorder NrZamowniaBezHash [uwagi]

frontend/views/rocket-chat/commands/history.php
<?php
/** @var $user \common\models\User */
/** @var $orders \common\models\Order[] */
/** @var $date string */
/** @var $dateTo string */

if (null === $user): ?>
    Brak integracji z ssorder użyj komendy `info`.
<?php else: ?>
    <?php if (empty($orders)): ?>
        Brak zamówień w dniach <?= $date ?> - <?= $dateTo; ?>.
    <?php else: ?>
        Twoje zamówienia z dnia <?= $date ?> - <?= $dateTo; ?>:
        <?php foreach ($orders as $order): ?>
            <?= $this->render('/rocket-chat/partials/order', ['order' => $order]); ?>
        <?php endforeach; ?>
    <?php endif ?>
<?php endif ?>

frontend/views/rocket-chat/commands/info.php
<?php
/** @var $user \common\models\User */
/** @var $request \frontend\rocketChat\models\Request */
?>

Wiadomość od <?= $request->user_name ?>, id rocketchat `<?= $request->user_id ?>`
<?php if (null === $user): ?>
    Nie masz integracji między ssorder a rocketchat :/
<?php else: ?>
    Twój login w ssorder to `<?= $user->username ?>`
<?php endif; ?>

frontend/views/rocket-chat/commands/last.php
<?php
/** @var $user \common\models\User */
/** @var $order \common\models\Order */

if (null === $user): ?>
    Brak integracji z ssorder użyj komendy `info`.
<?php else:
    if ($order): ?>
        Twoje ostatnie zamówienie z dnia <?= $order->data ?>
        <?= $this->render('/rocket-chat/partials/order', ['order' => $order]); ?>
    <?php else: ?>
        Jeszcze niczego nie zamówiłeś!
    <?php endif; ?>
<?php endif; ?>

frontend/views/rocket-chat/commands/order.php
<?php
/** @var $user \common\models\User */
/** @var $orders \common\models\Order[] */

if (null === $user): ?>
    Brak integracji z ssorder użyj komendy `info`.
<?php else: ?>
    <?php if (empty($orders)): ?>
        Brak zamówień w dniu dzisiejszym.
    <?php else: ?>
        Twoje dzisiejsze zamówienia:
        <?php foreach ($orders as $order): ?>
            <?= $this->render('/rocket-chat/partials/order', ['order' => $order]); ?>
        <?php endforeach; ?>
    <?php endif ?>
<?php endif ?>

frontend/views/rocket-chat/commands/reorder.php
<?php
/** @var $newOrder \common\models\Order */
?>

Złożono nowe zamówienie `#<?= $newOrder->id ?>` w restauracji _<?= $newOrder->restaurants->restaurantName ?>_ na żarcie *<?= $newOrder->getFoodName() ?>* za <?= Yii::$app->formatter->asCurrency($newOrder->getPrice()) ?>.
<?php if (!empty($newOrder->uwagi)): ?>
    UWAGI: <?= $newOrder->uwagi ?>
<?php endif; ?>